## 1.importing library

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
import joblib

## 2.load dataset

In [2]:
students=pd.read_csv("Student_Performance.csv")
students

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [3]:
students.isna().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

## 3. define X and Y

In [4]:
x=students[["Hours Studied","Previous Scores","Sleep Hours","Sample Question Papers Practiced"]]
x

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced
0,7,99,9,1
1,4,82,4,2
2,8,51,7,2
3,5,52,5,2
4,7,75,8,5
...,...,...,...,...
9995,1,49,4,2
9996,7,64,8,5
9997,6,83,8,5
9998,9,97,7,0
9999,7,74,8,1

In [5]:
y=students[["Performance Index"]]
y

      Performance Index
0                  91.0
1                  65.0
2                  45.0
3                  36.0
4                  66.0
...                 ...
9995               23.0
9996               58.0
9997               74.0
9998               95.0
9999               64.0

[10000 rows x 1 columns]

## 4.Split into training and testing sets (80% train, 20% test)

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [7]:
x_train

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced
9254,5,49,7,5
1561,2,48,7,6
1670,2,81,7,2
6087,2,46,6,1
6669,8,47,9,0
...,...,...,...,...
5734,8,50,6,6
5191,4,68,9,3
5390,9,48,7,6
860,1,47,9,0
7270,2,46,6,6

In [8]:
x_test

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced
6252,5,69,8,2
4684,2,46,4,8
1731,7,56,7,5
4742,6,42,8,5
4521,7,53,4,6
...,...,...,...,...
6412,2,70,7,3
8285,4,79,9,3
7853,2,40,7,2
1095,3,83,7,5
6929,5,60,8,4

In [9]:
y_train

      Performance Index
9254               36.0
1561               25.0
1670               59.0
6087               22.0
6669               40.0
...                 ...
5734               48.0
5191               51.0
5390               44.0
860                20.0
7270               24.0

[8000 rows x 1 columns]

In [10]:
y_test

      Performance Index
6252               51.0
4684               20.0
1731               46.0
4742               28.0
4521               41.0
...                 ...
6412               45.0
8285               66.0
7853               16.0
1095               65.0
6929               47.0

[2000 rows x 1 columns]

## 5. Train the model

In [11]:
model=LinearRegression()

In [12]:
model.fit(x_train,y_train)

LinearRegression()

## 6.Predict on test set

In [13]:
y_predict=model.predict(x_test)
y_predict

array([[55.00786377],
       [22.31444624],
       [47.59404705],
       ...,
       [16.48182916],
       [63.64243731],
       [46.23799491]], shape=(2000, 1))

## 7.Evaluate accuracy

In [14]:
mse = mean_squared_error(y_test, y_predict)
r2 = r2_score(y_test, y_predict)

In [15]:
print("Mean Squared Error (MSE):", mse)
print("R² Score:", r2)

Mean Squared Error (MSE): 4.182254914593818
R² Score: 0.9887144552384186

## 8.Visualization (training vs testing)

In [16]:
# plt.scatter(x_train, y_train, color='blue', label='Training Data')
# plt.scatter(x_test, y_test, color='green', label='Testing Data')
# plt.plot(x_train, model.predict(x_train), color='red', label='Regression Line')
# plt.xlabel("Hours Studied")
# plt.ylabel("Scores")
# plt.legend()
# plt.show()

## 9. save the trained model

In [17]:
joblib.dump(model,"simple_linear_model.pkl")
print("model saved successfully")

model saved successfully

In [18]:
load_model=joblib.load("simple_linear_model.pkl")
load_model

LinearRegression()

In [19]:
new_hours = [[6.5,89,6,4]]
predicted_score = load_model.predict(new_hours)
print("Predicted score for new score:", predicted_score)

Predicted score for new score: [[79.06473428]]

C:\Users\dell\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(